# Generated by Django 6.0.3 on 2026-03-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_badge_category_section_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorys',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sections',
            new_name='section',
        ),
    ]
