# Generated by Django 6.0.3 on 2026-03-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_original_price'),
        ('shop', '0005_cart_order_orderitem_cartitem'),
    ]

    operations = [
    ]
