# Generated by Django 6.0.3 on 2026-03-30 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Trail Notes', 'Trail Notes'), ('Gear Guide', 'Gear Guide'), ('Adventure Story', 'Adventure Story'), ('Pack Science', 'Pack Science'), ('How-To', 'How-To')], default='Trail Notes', max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('source', models.CharField(default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
